#!/usr/bin/env python3
"""
CLI for automatically varying PWM on a specified pin

author: Marion Anderson
date:   2018-06-18
file:   scanpwm
"""
from __future__ import absolute_import

import click
import pigpio


@click.command()
@click.argument('pin')
def main(pin):
    """Scans pwm settings on a Broadcom-numbered pin."""
    print('Starting scanpwm!')


    # startup
    pin = int(pin)
    pi = pigpio.pi()
    pi.set_servo_pulsewidth(pin, 0)  # force error if bad pin
    print('scanpwm initialized!\n')  # notify user of startup

    # control
    go = True
    while go:
        for i in range(500, 3000, 500):
            pi.set_servo_pulsewidth(pin, i)
            click.echo("Wrote {1}us to pin {0}".format(pin, i))

            val = input('Press enter to continue or type \'q\' to exit: ')
            if val == 'q' or val == 'exit' or val == 'quit':
                go = False
                break

    # shutdown
    pi.stop()

if __name__ == '__main__':
    main()
